--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/03/2020 11:30:06
-- Server version: 5.5.5-10.1.40-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS practica2yii_poo;

CREATE OR REPLACE DATABASE practica2yii_poo
	CHARACTER SET latin1
	COLLATE latin1_spanish_ci;

--
-- Set default database
--
USE practica2yii_poo;

--
-- Create table `noticias`
--
CREATE OR REPLACE TABLE noticias (
  id int(11) NOT NULL AUTO_INCREMENT,
  titulo varchar(255) DEFAULT NULL,
  texto varchar(255) DEFAULT NULL,
  foto varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET latin1,
COLLATE latin1_spanish_ci;

--
-- Create table `articulos`
--
CREATE OR REPLACE TABLE articulos (
  id int(11) NOT NULL AUTO_INCREMENT,
  titulo varchar(255) DEFAULT NULL,
  texto_corto varchar(255) DEFAULT NULL,
  texto_largo varchar(255) DEFAULT NULL,
  foto varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET latin1,
COLLATE latin1_spanish_ci;

-- 
-- Dumping data for table noticias
--
INSERT INTO noticias VALUES
(1, 'Noticia 1', 'Este es el texto de la noticia 1', 'fort_awesome.jpg'),
(2, 'Noticia 2', 'Este es el texto de la noticia 2', 'fort_awesome.jpg'),
(3, 'Noticia 3', 'Este es el texto de la noticia 2', 'fort_awesome.jpg'),
(4, 'Noticia 4', 'Este es el texto de la noticia 4', 'fort_awesome.jpg');

-- 
-- Dumping data for table articulos
--
INSERT INTO articulos VALUES
(1, 'Articulo 1', 'Texto 1', 'Texto largo 1', 'fort_awesome.jpg'),
(2, 'Articulo 2', 'Texto 2', 'Texto largo 2', 'fort_awesome.jpg'),
(3, 'Articulo 3', 'Texto 3', 'Texto largo 3', 'fort_awesome.jpg');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;